server:
  service:
    type: LoadBalancer
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:REGION:ACCOUNT:certificate/your-acm-cert-id
      alb.ingress.kubernetes.io/target-type: ip
    hosts:
      - argocd.yourdomain.com
    paths:
      - /
    tls:
      - hosts:
          - argocd.yourdomain.com
        secretName: argocd-tls
