version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: nehas91156/todo-backend:latest
    ports:
      - "8000:8000"
    
  frontend:
    build:
      context: ./frontend/todo
      dockerfile: Dockerfile
    image: nehas91156/todo-frontend:latest
    ports:
      - "3000:3000"

