apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80             # Required for Ingress
      targetPort: 8080     # Match the port in your backend Deployment/Pod
