apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend  # Ensure this matches the backend pod label
  ports:
    - port: 80
      targetPort: 8000  # Port of the backend container
  type: LoadBalancer
