apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP  # Default and preferred for Ingress routing
