apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80          # Must match the port in the Ingress definition
      targetPort: 8080  # Or whatever your container actually listens on
