apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80             # Required for Ingress
      targetPort: 3000     # Match the port in your frontend Deployment/Pod
