apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app  # Name of your ArgoCD application
spec:
  destination:
    name: 'aws.eks.my-eks-cluster.amazonaws.com'  # Replace with your EKS cluster name
    namespace: default  # Namespace where the app will be deployed in EKS
  source:
    repoURL: 'https://github.com/nehasharma1795/Todo-Terraform-HA-EKS.git'  # Replace with your repository URL
    path: 'manifests/'  # Path to the directory where your Kubernetes manifests are stored
    targetRevision: HEAD  # Use HEAD for the latest commit, or specify a branch/tag
  project: default  # Optional: Define which ArgoCD project to use (usually 'default')
  syncPolicy:
    automated:
      prune: true  # Automatically prune resources that are no longer in the repository
      selfHeal: true  # Automatically heal the application in case of drift

