name: CI/CD Pipeline for Todo App

on:
  push:
    branches: [main]

env:
  AWS_REGION: ap-south-1
  BACKEND_ECR_REPO: todo-backend
  FRONTEND_ECR_REPO: todo-frontend

jobs:
  build-and-push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set ECR Image URIs
        id: ecr-uris
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "BACKEND_IMAGE=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${BACKEND_ECR_REPO}" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${FRONTEND_ECR_REPO}" >> $GITHUB_ENV

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.BACKEND_IMAGE }}:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/todo
          file: ./frontend/todo/Dockerfile
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}:latest

