name: Deploy to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials from GitHub Secrets
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Authenticate Docker to AWS ECR
      - name: Authenticate Docker to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # Step 4: Set repository names from Terraform outputs (Backend and Frontend)
      - name: Set ECR repository names
        id: set_repo_names
        run: |
          echo "ECR_BACKEND_NAME=${{ secrets.ECR_BACKEND_NAME }}" >> $GITHUB_ENV
          echo "ECR_FRONTEND_NAME=${{ secrets.ECR_FRONTEND_NAME }}" >> $GITHUB_ENV

      # Step 5: Build Docker image for Backend
      - name: Build Docker image for Backend
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_BACKEND_NAME }}:latest .

      # Step 6: Push Docker image to Backend ECR
      - name: Push Docker image to Backend ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_BACKEND_NAME }}:latest

      # Step 7: Build Docker image for Frontend
      - name: Build Docker image for Frontend
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_FRONTEND_NAME }}:latest .

      # Step 8: Push Docker image to Frontend ECR
      - name: Push Docker image to Frontend ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_FRONTEND_NAME }}:latest

      # Step 9: Deploy to Kubernetes (Example - Helm upgrade for ArgoCD)
      - name: Deploy ArgoCD (example using Helm)
        run: |
          helm upgrade --install argocd argo/argo-cd \
            --namespace argocd \
            --set server.service.type=LoadBalancer \
            --set server.ingress.enabled=true \
            --set server.ingress.hosts[0]=argocd.${{ secrets.AWS_REGION }}.amazonaws.com

      # Step 10: Verify Ingress for Backend and Frontend
      - name: Verify Ingress for Backend and Frontend
        run: |
          kubectl get ingress backend-ingress
          kubectl get ingress frontend-ingress
          
      # Step 11: Monitor ALB logs (optional)
      - name: Monitor AWS Load Balancer Controller logs (optional)
        run: |
          kubectl logs -n kube-system deployment/aws-load-balancer-controller
          
      # Step 12: Notify (example - Slack notification, optional)
      - name: Send deployment success notification (optional)
        uses: slackapi/slack-github-action@v1.0.0
        with:
          slack-token: ${{ secrets.SLACK_TOKEN }}
          channel: '#deployments'
          text: "Deployment to AWS ECR and Kubernetes has been successfully completed!"

